### PR TITLE
Added support for Kotlin syntax

### PR DESCRIPTION
**Pull request by josevnz**
This pull request makes the following changes:
* Adds Kotlin syntax on the README.md file, very useful for those using this plugin.

Please let me know if something else needs to be fixed, improved.

Thanks!

It relates to the following issue #s:
* [Fixes #X](https://github.com/sonatype-nexus-community/scan-gradle-plugin/issues/71)

cc @bhamail / @DarthHater / @guillermo-varela / @shaikhu

### CODE REVIEW

**Comment by josevnz** [comment]
I signed the CLA too.

**Comment by DarthHater** [comment]
> I signed the CLA too.

Looks like we still need @kodegeek to sign it!

**Comment by guillermo-varela** [comment]
> > I signed the CLA too.
> 
> Looks like we still need @kodegeek to sign it!

For what I can tell @kodegeek is an alternative account of @josevnz 

If that's the case, please sign the CLA using the @kodegeek account as well.

**Comment by DarthHater** [comment]
> > > I signed the CLA too.
> > 
> > 
> > Looks like we still need @kodegeek to sign it!
> 
> For what I can tell @kodegeek is an alternative account of @josevnz
> 
> If that's the case, please sign the CLA using the @kodegeek account as well.

Or amend the commit to be @josevnz (but yeah, we need the account it was authored under, bots are only so smart!)

**Pull request closed without merging**
