### PR TITLE
Update to Gradle 8.8

### PR DESCRIPTION
**Pull request by guillermo-varela**
Goes up until the more recent Gradle version we can use without introducing breaking changes.

I'd prefer to deal with those changes later when we upgrade to Gradle 9 (which isn't yet at GA).

cc @bhamail / @DarthHater / @shaikhu

### CODE REVIEW

**Comment by guillermo-varela** [comment]
There is a known issue with Gradle and multi-jar dependencies on plugins, which happen to be the case of Jackson as of version 2.15.0-rc1.

While a workaround could be using resolution strategy to force a downgraded version it's hard to determine the impact (specially medium/long term) of using an older dependency version.

It migth be better just to work with what Gradle allow us to on each version where they fixed (or backported) the issue:
- https://github.com/FasterXML/jackson-core/issues/955
- https://github.com/gradle/gradle/issues/24390
- https://github.com/gradle/gradle/issues/27156
- https://github.com/gradle/gradle/pull/27633

**Comment by shaikhu** [comment]
> There is a known issue with Gradle and multi-jar dependencies on plugins, which happen to be the case of Jackson as of version 2.15.0-rc1.
> 
> While a workaround could be using resolution strategy to force a downgraded version it's hard to determine the impact (specially medium/long term) of using an older dependency version.
> 
> It migth be better just to work with what Gradle allow us to on each version where they fixed (or backported) the issue:

Fully in agreement with this. We probably need to update the readme or version 3 of this plugin, to state which gradle versions are supported.

**Review by shaikhu — APPROVED** [review]
+1

**Comment by guillermo-varela** [comment]
> We probably need to update the readme or version 3 of this plugin, to state which gradle versions are supported.

Please check if this is good enough: https://github.com/sonatype-nexus-community/scan-gradle-plugin/pull/165/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Pull request closed without merging**
