### PR TITLE
docs: Missing slashes before comments in README.md

### PR DESCRIPTION
**Pull request by pnu-s**
Hello there! :wave: 

When I first tried to use this tool I found out about 2 missing slashes which made my first execution fail (because I did not pay enough attention). So I figured out I'll open a PR to add them.

This pull request makes the following changes:
* add the missing slashes in the configuration example in `README.md`

I did not take the time to open an issue first as this is a very minor change, hope this is not a problem!

cc @bhamail / @DarthHater / @guillermo-varela / @shaikhu

### CODE REVIEW

**Comment by guillermo-varela** [comment]
Hi @pnu-s!

Thanks for submitting your PR, we deeply appreciate contributions :)

Once you sign the [CLA](https://sonatypecla.herokuapp.com/sign-cla) (required for our community projects) then we can merge this.

Let us know if you have questions about it.

**Comment by DarthHater** [comment]
@pnu-s I both agree and disagree with you. The CLA process while slowing things down a tiny bit, removes the need for us as developers to run each and every commit past a corporate lawyer to determine if it meets the criteria for needing a CLA signed (generally, and this is total I AM NOT A LAWYER speak, you need one when someone contributes intellectual property, such that they can't sue you or people who consume it later, later).

While I get it is a bit overkill (and we've done some talking about using a DCO in projects, but it's mostly me convincing the lawyers it is acceptable to do so without incurring legal risk), it does save us a ton of time, if you went back to Sonatype 4-5 years ago, we'd have to physically reach out as developers and get someone to actually sign a document and email it in. This feels incredibly modern as a result :)

I hope that explains a lil bit about it.

**Comment by DarthHater** [comment]
Beyond that, the LICENSE governs CONSUMPTION of this project (so usage), not CONTRIBUTIONS back to it, and the ensuing dance that creates. The CLA exists to govern that side of things, such that if you contribute something, and then later someone is using a project with your contribution, they (the consumer) don't have to worry that they will incur some legal risk, as in the contributor could come along and sue them etc..., the CLA handles the hand shake portion of that saying "Yeah, I give this code away, it's cool, I just want to contribute it".

**Comment by pnu-s** [comment]
Thanks @DarthHater for taking the time to give me such a detailed answer :) 

I'm not totally happy about it, but I signed it.

Cheers!

**Review by guillermo-varela — APPROVED** [review]
@pnu-s Thanks for your contribution :)

**Pull request merged**
